### ISSUE TITLE
Remove Shipping Method

### ISSUE THREAD

**Issue by hazenetwork91** [flaviocopes/grav-plugin-shoppingcart#22]
Hi,
i have a problem. when i try to checkout, i cant choose any shipping method because they don't get listed. i have left the example shipping methods in shoppingcart.yaml

As i can't fix it, how can i remove it completely from the formular? my client sells only digital items so this function won't be needed.

Thanks!

![screenshot at 2016-04-19 21 21 05](https://cloud.githubusercontent.com/assets/17365315/14652465/bdf9b490-0674-11e6-8a4a-6bae14ca8845.png)

**Comment by flaviocopes** [comment]
You need to setup at least a shipping option in your `user/config/plugins/shoppingcart.yaml` file.

https://github.com/flaviocopes/grav-plugin-shoppingcart/blob/master/shoppingcart.yaml#L10-L23

Add 

```yaml
shipping:
    methods:
        -
            name: Free shipping
            allowedCountries: ['*']
            price: 10
```

and it should work fine. 

Then you can hide it via CSS.

The next release will allow to remove this field altogether from the checkout form.
