### ISSUE TITLE
Problem with displaying order address on latest stable releases

### ISSUE THREAD

**Issue by jjui** [flaviocopes/grav-plugin-shoppingcart#26]
Tested different approaches in `shoppingcart_order.html.twig` as

```
{{ order_address.address }}
{{ order_address.address1 }}
{{ order_address.address2 }}
```

but none of them works, tho 

```
{{ order_address.zip }} 
{{ order_address.city }}
{{ order_address.country }}
```

is no problem. 
Referring to [original file](https://github.com/flaviocopes/grav-plugin-shoppingcart/blob/master/templates/shoppingcart_order.html.twig)

All latest stable releases.

**Comment by flaviocopes** [comment]
Depends on what data is stored in the order. What's an example of a order yaml?

**Comment by jjui** [comment]
Address is missing. From stored order: 
```
products:
    - { product: { title: 'SMOKE HOODIE', id: 12775582d8413eeab96fa04d185f4481, price: '999', defaultPhoto: /user/pages/01.shop-all/01.smoke-hoodie/135.jpg, type: '', url: '%2Fshop-all%2Fsmoke-hoodie' }, quantity: '1' }
address:
    firstname: Carl
    lastname: XII
    email: calle@bomb.ch
    telephone: '070000000'
    city: Wallisel
    zip: '7788'
    country: CH
    state: 'SMOKE HOODIE S '
    province: Zürich
shipping:
    method: '3-5 WORKINGDAYS - DHL'
    cost: '120.00'
payment:
    method: stripe
token and date etc
```
And  the current config for shoppingcart: 
```
            name: address
            type: text
            label: PLUGIN_SHOPPINGCART.CHECKOUT_ADDRESS
            classes: js__billing__address
            id: js__billing__address2
            validate:
                required: true
```
Know this issue will be removed with the update, but very annoying... ^^

**Comment by flaviocopes** [comment]
Ok so the issue is that it's not stored in the first place.

Paste your shoppingcart.yaml full form section and I'll try to replicate

**Comment by jjui** [comment]
Aight, here we go: 

```
checkout_form:
    name: checkout
    id: checkout_form
    fields:
        -
            type: display
            content: PLUGIN_SHOPPINGCART.CHECKOUT_HEADLINE_YOUR_PERSONAL_DETAILS
            markdown: true

        -
            name: firstname
            type: text
            label: PLUGIN_SHOPPINGCART.CHECKOUT_FIRST_NAME
            classes: js__billing__firstname
            id: js__billing__firstname
            validate:
                required: true
        -
            name: lastname
            type: text
            label: PLUGIN_SHOPPINGCART.CHECKOUT_LAST_NAME
            classes: js__billing__lastname
            id: js__billing__lastname
            validate:
                required: true

        -
            name: email
            type: email
            label: PLUGIN_SHOPPINGCART.CHECKOUT_EMAIL
            classes: js__billing__email
            id: js__billing__email
            validate:
                required: true

        -
            type: display
            content: PLUGIN_SHOPPINGCART.CHECKOUT_HEADLINE_YOUR_ADDRESS
            markdown: true

        -
            name: address
            type: text
            label: PLUGIN_SHOPPINGCART.CHECKOUT_ADDRESS
            classes: js__billing__address
            id: js__billing__address2
            validate:
                required: true

        -
            name: telephone
            type: text
            label: PLUGIN_SHOPPINGCART.CHECKOUT_PHONE
            id: js__billing__telephone
            classes: js__billing__telephone
            validate:
                required: true

        -
            name: city
            type: text
            label: PLUGIN_SHOPPINGCART.CHECKOUT_CITY
            classes: js__billing__city
            id: js__billing__city
            validate:
                required: true

        -
            name: zip
            type: text
            label: PLUGIN_SHOPPINGCART.CHECKOUT_ZIP
            classes: js__billing__zip
            id: js__billing__zip
            validate:
                required: true

        -
            name: country
            type: select
            label: PLUGIN_SHOPPINGCART.CHECKOUT_COUNTRY
            classes: js__billing__country
            id: js__billing__country
            validate:
                required: true

        -
            name: state
            type: select
            label: PLUGIN_SHOPPINGCART.CHECKOUT_STATE
            classes: js__billing__state
            outerclasses: js__billing__state__control
            id: js__billing__state

        -
            name: province
            type: text
            label: PLUGIN_SHOPPINGCART.CHECKOUT_PROVINCE
            classes: js__billing__province
            outerclasses: js__billing__province__control
            id: js__billing__province

        -
            type: display
            content: PLUGIN_SHOPPINGCART.CHECKOUT_SHIPPING_METHOD
            markdown: true

        -
            name: shipping_method
            type: select
            label: PLUGIN_SHOPPINGCART.CHECKOUT_CHOOSE_SHIPPING_METHOD_DESC
            classes: js__shipping__method
            outerclasses: checkout-choose-shipping-block
            id: js__shipping__method
            validate:
                required: true

        -
            type: display
            content: PLUGIN_SHOPPINGCART.CHECKOUT_PAYMENT_METHOD
            markdown: true
            outerclasses: checkout-choose-payment-block-title

        -
            name: payment_method
            type: select
            label: PLUGIN_SHOPPINGCART.CHECKOUT_CHOOSE_PAYMENT_METHOD_DESC
            classes: js__payment__method
            outerclasses: checkout-choose-payment-block
            id: js__payment__method

        -
            name: agree_to_terms
            type: checkbox
            id: agreeing_to_terms
            label: PLUGIN_SHOPPINGCART.TERMS_AND_CONDITIONS
            validate:
                required: true


    buttons:
        -
            type: submit
            value: PLUGIN_SHOPPINGCART.CHECKOUT_BUTTON_PAY

```
