### ISSUE TITLE
Product Variance Fonrmatter Example?

### ISSUE THREAD

**Issue by NedgoIO** [flaviocopes/grav-plugin-shoppingcart#48]
Could I please get a product variance frontmatter example?

**Comment by flaviocopes** [comment]
As replied in Gitter, you can use the Admin plugin to add variations, but also doable manually with for example:

```
title: 'Product title 2'
price: '19.99'
variations:
    -
        name: Color
        required: false
        options:
            -
                option: Black
            -
                option: White
```
